### ISSUE TITLE
[BUG] - Older A1111 png cause error in SD Prompt Reader comfyui node

### ISSUE THREAD

**Issue by dirtyapenz** [receyuki/comfyui-prompt-reader-node#43]
### Description

Example image: https://pasteboard.co/FfcxUpdd5JTB.png

Image settings: "Steps: 40, Sampler: DDIM, CFG scale: 7, Seed: 610501910, Size: 768x768, Model hash: 2c02b20a"

The model parameter is missing which I think is the cause of the issue.

Error from console:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/mnt/nvme2tb/github/ComfyUI/execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/nvme2tb/github/ComfyUI/execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/nvme2tb/github/ComfyUI/execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/nvme2tb/github/ComfyUI/custom_nodes/comfyui-prompt-reader-node/nodes.py", line 173, in load_image
    self.param_parser(image_data.parameter.get("model"), parameter_index)
  File "/mnt/nvme2tb/github/ComfyUI/custom_nodes/comfyui-prompt-reader-node/nodes.py", line 207, in param_parser
    data_list = data.strip("()").split(",")
AttributeError: 'NoneType' object has no attribute 'strip'

### Reproduction steps

1. SD Prompt Reader node
2. Add the example image to the SD Prompt Reader node
3. Press ctrl+enter

**Comment by receyuki** [comment]
You're right, I will fix this bug in the next release

**Comment by receyuki** [comment]
Please try the latest version.

**Comment by dirtyapenz** [comment]
> Please try the latest version.

The issue is resolved. Thank you.
