### ISSUE TITLE
Workflow can no longer be loaded after update

### ISSUE THREAD

**Issue by murphylanga** [receyuki/comfyui-prompt-reader-node#78]
### Description

Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of undefined (reading 'find')
TypeError: Cannot read properties of undefined (reading 'find')
    at nodeType.onGraphConfigured (http://127.0.0.1:8188/extensions/core/widgetInputs.js:359:29)
    at app.graph.onConfigure (http://127.0.0.1:8188/scripts/app.js:1406:29)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2260:9)
    at LGraph.configure (http://127.0.0.1:8188/scripts/app.js:1393:22)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:69:21)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1838:15)
    at async app.loadGraphData (http://127.0.0.1:8188/extensions/core/undoRedo.js:25:12)
    at async app.loadGraphData (http://127.0.0.1:8188/extensions/ComfyUI-Manager/components-manager.js:771:9)
    at async reader.onload (http://127.0.0.1:8188/scripts/app.js:2206:6)
This may be due to the following script:
/extensions/core/widgetInputs.js

Here you can find a workflow:
https://openart.ai/workflows/murphylanga/automatic_comfyui_sdxl_modul-incl-faceswap/2Bsh5QwsrQkKFx6CLCz7

### Reproduction steps

1 start comfy UI
2. load the workflow

**Comment by receyuki** [comment]
Sorry for the inconvenience. I mistakenly thought no one would use this special node. I've now reverted the problematic commit e8ca90fe35c1e12a3bfa3e277f732ff62e6b9c61.

For the problematic commit, its main purpose was to change the original `Type Converter` node into a more practical version with only one input and one output. To avoid impacting more people, I'll rename the new version to `Any Converter`.

**Comment by murphylanga** [comment]
Wow, you are fast. Thanks so much. I could have solved the Type Converter differently, but I still didn't know where I had to search. :-) But of course it's very nice for me.
Thank you again, also for your great work and the custom nodes.
But now I have to go to bed as quickly as possible.

**Comment by receyuki** [comment]
You can try using `Any Converter` node tomorrow. I personally think it'll be a better solution : )
